version: '3'

services:
  directory.api:
    image: directory.api:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_directory.api$
    volumes:
      - C:\AppDev\Arcnight\Directory\src\Directory.Api:/app
      - C:\Users\Arcnight\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_directory.api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_directory.api$ bin/Debug/netcoreapp2.0/Directory.Api.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
